openapi: 3.0.3
info:
  title: Users Service
  description: Microservice de gestion des utilisateurs pour un projet générique. Permet de créer, lire, modifier et supprimer des utilisateurs.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:

  /users/{pseudo}:
    parameters:
      - name: pseudo
        in: path
        schema:
          type: string
        example: Hunter2
        description: Pseudo de l'utilisateur

    post:
      summary: Créer un utilisateur
      requestBody:
        description: Données de l'utilisateur à créer
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Le pseudo en paramètre ne correspond pas au pseudo dans les données de l'utilisateur, ou les données ne correspondent pas à ce qui serait attendu
        409:
          description: Un utilisateur existe déjà avec ce pseudo
        201:
          description: L'utilisateur a été créé

    get:
      summary: Lire un utilisateur sur base de son pseudo
      responses:
        404:
          description: Aucun utilisateur n'a été trouvé pour ce pseudo
        200:
          description: Retourne les données de l'utilisateur correspondant
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/user'

    put:
      summary: Modifier un utilisateur sur base de son pseudo
      requestBody:
        description: Nouvelles données de l'utilisateur
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Le pseudo en paramètre ne correspond pas au pseudo dans les données de l'utilisateur, ou les données ne correspondent pas à ce qui serait attendu
        404:
          description: Aucun utilisateur n'a été trouvé pour ce pseudo
        200:
          description: L'utilisateur a été modifié

    delete:
      summary: Supprimer un utilisateur sur base de son pseudo
      responses:
        404:
          description: Aucun utilisateur n'a été trouvé pour ce pseudo
        200:
          description: L'utilisateur a été supprimé

components:
  schemas:
    user:
      type: object
      properties:
        pseudo:
          type: string
          description: Pseudo de l'utilisateur
        firstname:
          type: string
          description: Prénom de l'utilisateur
        lastname:
          type: string
          description: Nom de l'utilisateur
      example:
        pseudo: Hunter2
        firstname: Clara
        lastname: Dubois